modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="sigil_of_the_banished"
version="1.0.0"
displayName="Sigil of the Banished"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="mikey, MCreator"

[[dependencies.sigil_of_the_banished]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



